"use client";

import Head from "next/head";
import Image from "next/image";
import {useState, useEffect} from "react";
import localFont from "@next/font/local";
import {useRef} from "react";
import gsap from "gsap";
import {useGSAP} from "@gsap/react";
import Link from "next/link";

import Carousel from "../components/Carousel";
import VideoComponent from "../components/Videos";

import mohaimin from "../public/mohaimin-website-developer.webp";
import jobCyGif from "../public/recentProjectGif/jobcyproject.gif";
import tldGif from "../public/recentProjectGif/tldproject.gif";
const gunterzFont = localFont({
  src: "./fonts/headingnow/HeadingNowTrial-55Medium.ttf",
});

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  // GSAP CODE ----------------------------------------------------------------------------------------------------- Start
  const mainImage = useRef();
  useGSAP(() => {
    gsap.to(".mainImage", {rotation: "+=360", duration: 3});

    // or refs...
    gsap.to(mainImage.current, {rotation: "-=360", duration: 3});
  });
  // GSAP CODE ----------------------------------------------------------------------------------------------------- End

  return (
    <>
      <Head>
        <title>Mohaimin Islam: Frontend Website Developer (Bangladesh)</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/website-developer-mohaimin.svg" /> */}
        <link rel="icon" href="/website-developer-mohaimin-kaligraphy.svg" />
      </Head>
      <main className="bg-[#EEEFFF] min-h-[100vh]">
        <section className="mainSection">
          {/* Left side Section Start  */}
          <div className="MainLeft">
            {/* Profile Image Start */}
            <div className="profileImageDiv">
              <Link href={"/"}>
                <Image
                  priority
                  placeholder="blur"
                  quality={100}
                  className="profileImage"
                  src={mohaimin}
                />
              </Link>
            </div>
            {/* Profile Image End */}

            {/* Profile Text Start */}
            <div className="textDiv">
              <h1 className="name">
                M <span className="o"></span> haimin
              </h1>
              <h2 className="bio">Website developer | Webflow</h2>
              <h3 className="smallBio">
                Expert Low-Code/No-Code Developer | Webflow & Framer Designer &
                Developer | Driving Innovation and Efficiency
              </h3>
            </div>
            {/* Profile Text End */}
            {/* Buttons Start  */}
            <div className="MainButtonSection">
              <div className="leftButtons">
                <Link
                  href={
                    "mailto:programmermohaimin@gmail.com?subject=subject&message=message"
                  }
                  className="button bigButton contactBtn"
                >
                  Contact
                </Link>
                <Link className="button" href={"/pricing"}>
                  Pricing
                </Link>
                <Link
                  href={"https://www.linkedin.com/in/mohai/"}
                  target="_blank"
                  className="button"
                >
                  LinkedIn
                </Link>
              </div>
              <div className="leftButtons">
                <Link className="button" href={"/process"}>
                  Projects
                </Link>
                <Link className="button" href={"/linkedIn"}>
                  Reviews
                </Link>
                <Link className="button bigButton" href={"/contact"}>
                  Blogs
                </Link>
              </div>
            </div>
            {/* Buttons End  */}
          </div>

          {/* Right side Section Start  */}
          <div className="mainRightSide">
            {/* Focal Point Start  ---------------------------------------------------*/}
            <div className="focalDiv">
              <Carousel />
            </div>
            {/* Happy Clients Section Start  */}
            <div className="happyClientsMainDiv">
              <h2 className="bio">Clients Review</h2>
              {/* <div className="happyClientsVideoDiv">
                <div className="happyClientVideo"></div>
              </div> */}
              <VideoComponent />
            </div>

            {/* Recent Section Start  */}
            <div className="recentProjectsMainDiv">
              <h2 className="bio">Recent Works</h2>
              <div className="recentProjectsDiv">
                <Link
                  target="_blank"
                  className="recentProject"
                  href={"https://www.jobs.com.cy/"}
                >
                  <Image
                    width={200}
                    height={100}
                    className="recentProjectGif"
                    src={jobCyGif}
                  />
                </Link>
                <Link
                  target="_blank"
                  className="recentProject"
                  href={"https://tldstudio.xyz/"}
                >
                  <Image
                    width={200}
                    height={100}
                    className="recentProjectGif"
                    src={tldGif}
                  />
                </Link>

                <Link
                  target="_blank"
                  className="recentProject"
                  href={"https://rey-xpress.com/"}
                >
                  <Image
                    width={200}
                    height={100}
                    className="recentProjectGif"
                    src={jobCyGif}
                  />
                </Link>
              </div>
            </div>
          </div>
          {/* Right side Section End  */}
        </section>
      </main>
    </>
  );
}
