import Head from 'next/head'
import Image from 'next/image'
import moon from '../public/moon.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mohaimin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <nav className='flex items-center justify-between max-w-7xl m-auto px-4 mb-12'>
            <h1 className='text-gray-700 font-semibold text-2xl text-left py-4 cursor-pointer'>DevByMohaimin</h1>

            <ul className='flex items-center justify-between '>
              <li className='w-10 h-10 cursor-pointer'><Image src={moon} alt="moon"/></li>
              <li><a className='border-none px-8 py-2 m-4 border-black text-black font-semibold text-1xl rounded-full bg-gradient-to-r from-cyan-300 to-cyan-500' href='#'>Resume</a></li>
            </ul>
          </nav>

          

       </section>
      </main>

      
    </div>
  )
}
