import Head from "next/head";
import Image from "next/image";
import localFont from "@next/font/local";
const gunterzFont = localFont({
  src: "./fonts/gunterz/Fontspring-DEMO-gunterz-black.otf",
});

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import {BsFillMoonStarsFill} from "react-icons/bs";
import mohaimin from "../public/mohaimin-website-developer.webp";
import code from "../public/code.png";
import webflow from "../public/webflow.png";
import squarespace from "../public/squarespace.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";
import {AiFillCopyrightCircle} from "react-icons/ai";
import MessengerCustomerChat from "react-messenger-customer-chat";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohaimin Islam: Frontend Website Developer (Bangladesh)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 dark:bg-gray-900 dark:text-white">
        <section>
          <nav className="flex items-center justify-between max-w-7xl m-auto mb-12">
            <a
              href="/"
              className={`${gunterzFont.className} font-semibold text-xl text-left py-4 cursor-pointer sm:text-3xl font-[gunterzFont]`}
            >
              Mohaimin
            </a>

            <ul className="flex items-center justify-between ">
              <li className="cursor-pointer text-3xl">
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li className="hover:scale-105 duration-100 inline-block m-4">
                <a
                  className="border-none px-8 py-2 border-black text-black font-semibold text-1xl rounded-full bg-gradient-to-r from-cyan-300 to-cyan-500"
                  href="https://calendly.com/mohai/30min"
                >
                  Let's Chat!
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center ">
            <h1
              className={`${gunterzFont.className} text-cyan-600 font-semibold text-5xl py-2 md:text-7xl md:mt-20`}
            >
              Mohaimin Islam
            </h1>
            <h2 className="font-semibold text-2xl pb-4">
              Frontend Website Developer (Bangladesh)
            </h2>
            <p className="text-gray-500 dark:text-gray-400 font-normal text-lg md:text-xl max-w-lg mx-auto">
              I craft beautiful and functional websites using custom code and
              platforms like Webflow & Squarespace.
            </p>
          </div>

          <div className="flex items-center justify-center text-4xl space-x-8 mt-8">
            <a href="https://github.com/ProgrammerMohaimin">
              {" "}
              <AiFillGithub />
            </a>
            <a href="https://youtube.com/ProgrammerMohaimin">
              {" "}
              <AiFillYoutube />
            </a>
            <a href="https://twitter.com/DevMohaimin">
              {" "}
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/programmermohaimin/">
              {" "}
              <AiFillLinkedin />
            </a>
          </div>

          <div className="overflow-hidden relative bg-gradient-to-t from-white to-teal-500 rounded-full w-80 h-80 mx-auto mt-20 md:w-96 md:h-96 ">
            <Image
              layout="fill"
              objectFit="cover"
              src={mohaimin}
              alt="Mohaimin"
            />
          </div>

          <div className="max-w-3xl mx-auto px-4 my-20 ">
            <h1 className="font-semibold text-4xl text-left lg:text-center py-4 border-b-2">
              Services I Offer
            </h1>
            <p className="text-gray-500 dark:text-gray-400 font-normal text-xl text-left py-2 lg:text-center">
              I'm Mohaimin Islam, a frontend website developer in Bangladesh
              specializing in creating{" "}
              <span className="text-teal-500 font-semibold">
                beautiful and functional
              </span>{" "}
              websites using a blend of{" "}
              <span className="text-teal-500 font-semibold">custom code</span>{" "}
              and user-friendly platforms like{" "}
              <span className="text-teal-500 font-semibold">
                Webflow and Squarespace.
              </span>{" "}
              Whether you require a fully customized website built from scratch{" "}
              <span className="text-teal-500 font-semibold">
                (HTML, CSS, Javascript, ReactJs, NextJs)
              </span>{" "}
              or a sleek and modern design crafted within Squarespace's
              intuitive interface, I have the expertise to bring your vision to
              life.
              <span className="text-teal-500 font-semibold"></span>
            </p>
          </div>

          <div className="grid xl:grid-cols-3 max-w-[1600px] m-auto mb-12">
            {/* another card */}
            <div className="hover:shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] duration-200 px-4 shadow-xl m-4 rounded-lg text-center p-8 mt-12 dark:shadow-blue-500/50 dark:shadow-2xl">
              <Image height={130} width={130} src={code} alt="Gallery" />
              <h1 className="font-semibold text-2xl  py-4">
                Custom Website Development
              </h1>
              <p className="text-gray-500 dark:text-gray-400 font-normal text-lg max-w-md mx-auto">
                Bring your unique vision to life with custom-built websites. I
                specialize in crafting high-performance websites using modern
                programming languages (HTML, CSS, JavaScript) and frameworks.
                Whether you need a complex e-commerce platform, a dynamic
                single-page application, or a simple yet impactful landing page,
                I can create a website that perfectly aligns with your brand and
                objectives. Let's discuss your specific requirements and build a
                website that sets you apart.
              </p>
              <li className="list-none mt-[15px] hover:scale-105 duration-100 inline-block">
                <a
                  className="border-none px-8 py-2 border-black text-black font-semibold text-1xl rounded-full bg-gradient-to-r from-cyan-300 to-cyan-500"
                  href="https://docs.google.com/document/d/1bVAfR2IIMmm5b14eZhxuk09pCjpt_nFdFlC8hri_dhI/edit?usp=sharing"
                >
                  Message Now!
                </a>
              </li>
            </div>

            {/* another card */}
            <div className="hover:shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] duration-200 px-4 shadow-xl m-4 rounded-lg text-center p-8 mt-12 dark:shadow-blue-500/50 dark:shadow-2xl">
              <Image height={130} width={130} src={webflow} alt="Gallery" />
              <h1 className="font-semibold text-2xl py-4">
                Webflow Development
              </h1>
              <p className="text-gray-500 dark:text-gray-400 font-normal text-lg max-w-md mx-auto">
                Unlock the full potential of Webflow for your next website
                project. As a skilled Webflow developer, I can create
                interactive and dynamic websites with powerful CMS
                functionalities. Webflow allows for complete design freedom
                while maintaining clean and manageable code. Whether you need a
                custom animation, a unique user interaction, or a complex
                data-driven website, I can leverage Webflow's capabilities to
                deliver exceptional results.
              </p>
              <li className="list-none mt-[15px] hover:scale-105 duration-100 inline-block">
                <a
                  className="border-none px-8 py-2 m-4 border-black text-black font-semibold text-1xl rounded-full bg-gradient-to-r from-cyan-300 to-cyan-500"
                  href="https://docs.google.com/document/d/1bVAfR2IIMmm5b14eZhxuk09pCjpt_nFdFlC8hri_dhI/edit?usp=sharing"
                >
                  Message Now!
                </a>
              </li>
            </div>

            {/* another card */}
            <div className="hover:shadow-[0_35px_60px_-15px_rgba(0,0,0,0.3)] duration-200 px-4 shadow-xl m-4 rounded-lg text-center p-8 mt-12 dark:shadow-blue-500/50 dark:shadow-2xl">
              <Image height={130} width={130} src={squarespace} alt="Gallery" />
              <h1 className="font-semibold text-2xl py-4">
                Squarespace Website Design
              </h1>
              <p className="text-gray-500 dark:text-gray-400 font-normal text-lg max-w-md mx-auto">
                Get a beautiful and functional website up and running quickly
                with Squarespace. I leverage the power of Squarespace to design
                user-friendly and visually stunning websites. This platform is
                perfect for businesses or individuals who need a clean, modern
                website without the complexity of custom coding. I can handle
                the design, development, and launch, allowing you to focus on
                running your business.
              </p>
              <li className="list-none mt-[15px] hover:scale-105 duration-100 inline-block">
                <a
                  className="border-none px-8 py-2 m-4 border-black text-black font-semibold text-1xl rounded-full bg-gradient-to-r from-cyan-300 to-cyan-500"
                  href="https://docs.google.com/document/d/1bVAfR2IIMmm5b14eZhxuk09pCjpt_nFdFlC8hri_dhI/edit?usp=sharing"
                >
                  Message Now!
                </a>
              </li>
            </div>
          </div>
        </section>
        <section>
          <div className="max-w-5xl mx-auto my-8 ">
            <h1 className="mt-40 font-semibold text-3xl text-left py-4 lg:text-center">
              Portfolio
            </h1>
            <p className="text-gray-500 dark:text-gray-400 font-normal text-xl text-left py-2 xl:text-center">
              I am a programmer mohaimin and I am learning web development .
              Still now I am a{" "}
              <span className="text-teal-500 font-semibold">
                Front-end Developer
              </span>
              , But in future I wanted to become e Full-Stack Developer. I have
              own plan and I create a Company near future. I will help you to
              make{" "}
              <span className="text-teal-500 font-semibold">your dream</span> on
              your project.
            </p>
            <p className="text-gray-500 dark:text-gray-400 font-normal text-xl text-left py-2 xl:text-center">
              I will help you to make your dream on your project. I wanted to
              become e{" "}
              <span className="text-teal-500 font-semibold">
                {" "}
                Full-Stack Developer
              </span>
              .
            </p>
          </div>
          <div className=" md:flex md:flex-row md:flex-wrap">
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web1"
              />
            </div>
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web2"
              />
            </div>
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web3"
              />
            </div>
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web4"
              />
            </div>
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web5"
              />
            </div>
            <div className="basis-1/3 p-4 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="web6"
              />
            </div>
          </div>
        </section>
        <footer className="mt-40">
          <div className="flex items-center justify-center text-4xl space-x-8 my-8">
            <a href="https://github.com/ProgrammerMohaimin">
              {" "}
              <AiFillGithub />
            </a>
            <a href="https://youtube.com/ProgrammerMohaimin">
              {" "}
              <AiFillYoutube />
            </a>
            <a href="https://twitter.com/DevMohaimin">
              {" "}
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/programmermohaimin/">
              {" "}
              <AiFillLinkedin />
            </a>
          </div>
          <p className="text-center text-xl">
            Developed by{" "}
            <AiFillCopyrightCircle className="inline-block text-2xl" />{" "}
            Mohaimin_ 2022
          </p>
        </footer>
        <MessengerCustomerChat
          pageId="102306715670926"
          appId="487326113363644"
        />
        ,
      </main>
    </div>
  );
}
