import React from "react";
import PricingPlan from "../../components/PricingPlan";
import Head from "next/head";

const Pricing = () => {
  return (
    <>
      <Head>
        <title>Mohaimin Islam: Frontend Website Developer (Bangladesh)</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/website-developer-mohaimin.svg" /> */}
        <link rel="icon" href="/website-developer-mohaimin-kaligraphy.svg" />
      </Head>
      <PricingPlan />
    </>
  );
};

export default Pricing;
